Algoritmo "convertendo temperatura do eua para o brasil"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/05/2022
Var
// Seção de Declarações das variáveis 
    f, c:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
     escreva("qual é a tempratura aqui nos EUA? ")
     leia(f)
     c <- (f-32) /1.8
     escreva("a temperatura no Brasil seria ", c:4:1)

Fimalgoritmo