Algoritmo "semnome"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Thiago fernando dos santos
// Data atual  : 03/05/2022
Var
// Seção de Declarações das variáveis 

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 Escreval("Olá, Mundo!")
 Escreval("como vai vocês?")
 Escreva("Esse é o meu primeiro Algprismo é um momento muito especial para mim e tenho a agredecer ao pessoal da Unica então obrigado!!")
Fimalgoritmo