Algoritmo "Operadores"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/05/2022
Var
// Seção de Declarações das variáveis 
   A,B,C: Inteiro

Inicio
     escreval("escreva um numero")
     leia(A)
     escreval("escreva outro numero")
     leia(B)
     escreval("escreva outro numero")
     leia(C)
     
      A<-2
      B<-6
      C<-8
      Escreva ((C<A) ou (B+A=C))

Fimalgoritmo