Algoritmo "Melhorescola"

Var
   escol:inteiro
   etec_mcm:caractere
Inicio
   escreval("Qual e a melhor escola de Riberão Pires: ")
    escreval("OBS:se for dar espaço por favor use _ obrigado")
   leia(escol)
   enquanto (escol<> etec_mcm) faca
      escrevaL("ERROU TENTE NOVAMENTE")
      escreval("Qual e a melhor escola de Riberão Pires: ")
      leia(escol)
   fimenquanto
   escreva("Concordo")
FimAlgoritmo